### ISSUE TITLE
Giovanni (first year BSc student): lectures/courses with accented letters aren't displayed correctly.

### ISSUE THREAD

**Issue by enricocarraro** [se2team3/PULSeBS#54] opened 2020-12-17 14:56 UTC

**Comment by lucarinelli** [comment] 2021-01-03 22:52
Hi @enricocarraro,
I investigated the problem and I found out it is caused by the fact that the .csv we were using during the demo, the one originally provided by the professor, is encoded in a deprecated "mac roman" used only by Office for Mac in these days, that is detected as UTF8 by most of the programs you can open it with.
Support for this encoding on any program that is not Office for Mac is really bad. VSCode detects it as UTF8, same for gedit, Libreoffice Calc, Sublime Text Editor... Libraries that detect encodings in JavaScript do not support this Mac Roman encoding either, we would need to provide support for it ourselves.
Given the effort we already put in this we ended up now supporting most modern encodings, but we see no way to support correctly this encoding in our limited time budget.
We think is reasonable to ask the user to provide a file that uses a not so old encoding and so we are probably not going to put any more effort on this issue.
How did your team solved this problem? We are open to suggestions.

**Comment by lucarinelli** [comment] 2021-01-03 22:53
If this is all right with you feel free to close the issue

**Closed** 2021-01-09 16:57 UTC
Labels: Not gonna fix this... sorry
